[lib]
crate-type = ["cdylib"]

[package]
name = "rusty"
version = "0.1.0"
edition = "2021"


[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
[dependencies]
libc = "0.2"
goblin = "0.8.2"
